name: "Dizipal" # Sadeleşti
description: "Dizipal İçerikleri" # Güncellendi
version: "1.3.1" # server.js ile uyumlu
slug: "fusion_dizipal"
url: "https://github.com/dzirambola/fusion-dizipal-addon"

# Görünüm Ayarları
panel_icon: "mdi:play-box-outline"
panel_title: "Dizipal"
# GitHub'daki Raw logonuz:
icon: "https://raw.githubusercontent.com/dzirambola/fusion-dizipal-addon/main/fusion_dizipal/image_0.png"

# ... (Geri kalan build_from, ports vb. kısımlar aynı kalıyor)

arch:
  - aarch64
  - armv7
  - amd64
